### ISSUE TITLE
Update goggles logo

### ISSUE THREAD

**Issue by kristinashu** [mozilla/x-ray-goggles#219]
Looks like we haven't been using the correct logo (missing purple where pink and blue overlap). 

@kristinashu will export logo then give to @Pomax to implement.

**Comment by kristinashu** [comment]
The logo was design to use a multiply effect which isn't working on the dark purple header. We are going to have to use two logos - one for dark backgrounds (header) and one for light backgrounds (everywhere else). 

Images are attached and also here: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLRWs2V016WjhHZ2c&usp=sharing

![logo-dark](https://cloud.githubusercontent.com/assets/1068783/10805926/d1418358-7d8e-11e5-8898-60ec86b6ba08.png)
![logo](https://cloud.githubusercontent.com/assets/1068783/10805925/d1400834-7d8e-11e5-9f2f-7ef83b6212b7.png)

**Comment by cassiemc** [comment]
@kristinashu can you post a couple example of these in situ?

**Comment by kristinashu** [comment]
@cassiemc yeah for sure. I know the version that works on a dark background looks funny on white. 

v1 shows the original logo which has a multiply effect (gets lost on the dark background)
v2 has a dark purple where the colours intersect (really doesn't work)
v3 and v4 have blue-ish center (I think either of these work on the dark background but not on light)

<img width="542" alt="screen shot 2015-10-29 at 9 32 37 am" src="https://cloud.githubusercontent.com/assets/1068783/10824979/24c481c4-7e20-11e5-959a-1c73d5f76a21.png">

Let me know if you have any thoughts, thanks!

**Comment by Pomax** [comment]
Hmm, I kind of like the muted blue for both. For the dark background it feels like the only really good candidate, for light muted as well as multiply work, but of course the dev in me goes "that means muted is easiest because it's one logo" =P

**Comment by cassiemc** [comment]
@lovegushwa would love your thoughts here.

**Comment by lovegushwa** [comment]
@cassiemc I agree with @kristinashu that we probably need two versions. I suspect we wont use this on any other color background than purple or white. 

I actually think what's up on staging is the best option on Purple.  I'm curious how the same version would look on white? 

(this site is looking beautiful! ... The typography is slightly different than thimble, I'm sure you have this in mind but it would be good to change one or the other to match.)
<img width="759" alt="screen shot 2015-10-30 at 8 41 32 am" src="https://cloud.githubusercontent.com/assets/12228435/10850325/2e8af996-7ee2-11e5-9331-abe9ab7f56d2.png">

Favicon also currently looking good. Looks like this tiny option has no overprinting which is a great move at this size.)
<img width="126" alt="screen shot 2015-10-30 at 8 50 43 am" src="https://cloud.githubusercontent.com/assets/12228435/10850521/66786644-7ee3-11e5-9ec9-574d170baf24.png">

**Comment by kristinashu** [comment]
Thanks @lovegushwa for weighing in. 

Here's the staging logo on white (probably too pink?):
<img width="1225" alt="screen shot 2015-10-30 at 2 13 50 pm" src="https://cloud.githubusercontent.com/assets/1068783/10858224/9e549fd8-7f10-11e5-8f68-f3af9b4f5ef2.png">

Do you think we should keep what's on staging for the header and fav icon but update to the original logo on white?

Yeah it's weird how Fira is different on Thimble and Goggles (and then Webmaker and Goggles are the same). They are the same weights and sizes but I think they're hosted differently or something. Will sort out before launch.
