### ISSUE TITLE
Sign in or Sign up buttons not displaying correctly in Safari 8

### ISSUE THREAD

**Issue by hannahkane** [mozilla/x-ray-goggles#222]
![screen shot 2015-10-20 at 12 48 29 pm](https://cloud.githubusercontent.com/assets/8389648/10619255/7463b432-7729-11e5-9151-f31d2fc455c0.png)

**Comment by Pomax** [comment]
After updating Safari to the latest version using the App Store (which gave me Safari 9), I cannot reproduce this.
