### ISSUE TITLE
animate bubbles on FTU page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/x-ray-goggles#233]
Related to implement the FTU page #229 

Animate bubbles like in Invision when you go to it the first time (https://invis.io/F44O6ZJGY) but instead of continuously moving up and down it could maybe just do one bounce and then stop.

This is a nice-to-have enhancement we can save for the end.

**Comment by kristinashu** [comment]
@Pomax this is something Cassie would really like to see :)

**Comment by cassiemc** [comment]
I wonder if this is something @flukeout could help with if we're running short on time?

**Comment by flukeout** [comment]
Sure thing - I'll start on it now. I'll try it with a couple of bounces and then a stop, otherwise the text will be hard to read.

**Comment by cassiemc** [comment]
@flukeout Did you see the invision example? I think it was a really slow hover up and down, like a cloud. I'm not opposed to blatantly stealing that, if your idea doesn't work out.

**Comment by flukeout** [comment]
@cassiemc Yeah, took a good look at it! Basically did the same thing with @kristinashu's input except we limited it to 3 wobbles - the larger bubbles with more content are hard to read when constantly in motion. 

Let's take a look when @Pomax gets it to staging.

**Comment by Pomax** [comment]
merged in, should be on https://goggles-mozilla-org-staging.herokuapp.com shortly
