### ISSUE TITLE
Set up goggles prod

### ISSUE THREAD

**Issue by Pomax** [mozilla/x-ray-goggles#251]
We'll need to set up a prod instance of goggles that hooks into real webmaker login

- [x] create heroku instance
  - https://x-ray-goggles.herokuapp.com
- [x] add to x-ray-goggles heroku pipeline
  - github.com/mozilla/goggles.webmaker.org/tree/master auto-deploys to staging, prod deploy is a pipeline promotion on heroku
- [x] add goggles site+library client ids to id.wmo `clients` table on id-prod 
- [x] point goggles.mozilla.org to the above-created instance?
/cc @jbuck

**Comment by Pomax** [comment]
It looks like id.mofostaging is running the latest code, with a patch that fixes a CORS issue due to a workaround we had for `/user` for an older version of HAPI. The id-prod instance does not appear to be running that code yet, so authentication on goggles gets CORS-rejected when calling the `/user` route on id-prod.

**Comment by hannahkane** [comment]
This is done, right?

**Comment by Pomax** [comment]
yep! last checkmark had been overlooked - closing
