### ISSUE TITLE
make the old library throw a notice that we're now on goggles.mozilla.org

### ISSUE THREAD

**Issue by Pomax** [mozilla/x-ray-goggles#269]

**Comment by Pomax** [comment]
@hannahkane @kristinashu I mocked up something to replace the goggles library on the old location, to get people to bookmark the new goggles lib instead, but it'll need some copy and styling massaging - http://jsbin.com/qovobewomi/edit?html,js,output has a mockup (press "test" to simulate starting the goggles) which pops up a notice and can be dismissed by clicking on it again.

**Comment by hannahkane** [comment]
Nice, @Pomax.

I like your copy! Here are some suggested edits:
The X-Ray Goggles bookmark has moved!

X-Ray Goggles has a new home at https://goggles.mozilla.org! Head on over and follow the instructions to get the new bookmarklet. While you're there, have a look at the new sample activity. How many animals can you make?

**Comment by Pomax** [comment]
updated the jsbin, http://jsbin.com/ruzemawibu/edit?js,output has the new copy and some more googglesy coloring

**Comment by hannahkane** [comment]
nice!

can the styles for this be found in the style guide, @kristinashu ?

**Comment by Pomax** [comment]
(hopefully; I reused the ones we have on the goggles homepage atm)

**Comment by kristinashu** [comment]
Yeah the styles are consistent with the goggles site. We don't really have a style guide tho?

**Comment by hannahkane** [comment]
you mean we don't have a style guide for goggles specifically? hmm...maybe something to think about, though I don't expect a tremendous amount of development on it moving forward. anyway...looks good, @Pomax!

**Comment by Pomax** [comment]
let me package this up as a more-real-er .js library and have a look at how much work slotting that into the old location will be

**Comment by kristinashu** [comment]
Right, no style guide for goggles specifically but hopefully it will eventually be part of the master mofo style guide!

**Comment by Pomax** [comment]
I've committed https://github.com/mozilla/x-ray-goggles/blob/master/upgrade-goggles.js but it has not yet replaced the library as is currently hosted on the old goggles site.

**Comment by Pomax** [comment]
this was implemented and deployed
