### ISSUE TITLE
Styles not appearing on Remixed page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/x-ray-goggles#270]
Here's a Remix I made of the NYTimes: https://d157rqmxrxj6ey.cloudfront.net/hannahkaneei/31437/

![screen shot 2016-02-08 at 11 39 54 am](https://cloud.githubusercontent.com/assets/8389648/12896763/b31af592-ce58-11e5-9209-0f7cd6380cdf.png)

Similar result on BBC website.

Is this user error? Am I doing something so that the styles don't appear on the remix?

**Comment by Pomax** [comment]
mixed content - you remixed the http version of the new york times, and we publish on https, so all the http .css resources get blocked because they're potentially insecure.

**Comment by gideonthomas** [comment]
what's interesting is that the remix button does not appear in the published project

**Comment by gideonthomas** [comment]
it looks like the remix script is not being injected into that project

**Comment by gideonthomas** [comment]
uhh whoops, wrong project, sorry :P

**Comment by Pomax** [comment]
heh, no remix button on goggles (yet)

**Comment by gideonthomas** [comment]
interestingly I was able to remix that project in thimble by getting the project id from the url and adding it to the remix url like so: `https://thimble.mozilla.org/projects/31437/remix`, so that's a good sign :)

**Comment by Pomax** [comment]
yes. if you have database access and can look up its id, you can remix. Generally not a thing most users can do though =)

**Comment by gideonthomas** [comment]
lol sure...will file it on publish and investigate

**Comment by hannahkane** [comment]
Hmm...I wonder how often users run into this problem. Can we throw a warning or something if people are remixing mixed content?

**Comment by Pomax** [comment]
it's pretty much the "http and https do not play well together" teaching moment. Especially with the move to https everywhere (in which letsencrypt is one of the many initiatives) it's one of those things that people new to the web will keep running into. We might be able to detect whether the page will have issues by checking `<link>` and `<script>` elements for source protocols. Filed as https://github.com/mozilla/x-ray-goggles/issues/271

**Comment by hannahkane** [comment]
Cool. Thanks. Closing this ticket!
