### ISSUE TITLE
X-Ray Goggles Not Loading

### ISSUE THREAD

**Issue by williamaberry11** [mozilla/x-ray-goggles#276]
Hello,

I am using the X-Ray Goggles with a small group of students as an introduction to coding. Two days ago, we all used the Goggles and they worked just fine. Yesterday, when attempting to use the Goggles via the bookmarklet we installed, there was absolutely no response. We are all using Google Chrome or Firefox. 

Have there been issues with the Goggles reported in the past day or two?

Thanks so much,

William Berry

**Comment by Pomax** [comment]
does your console say anything? We replaced the old bookmarklet with a new one that pops up a notice tell you that goggles now lives on goggles.mozilla.org and that you can rebookmark the new and improved version from there. If you don't see that notice when you start the old bookmark, it'll be very useful to know if the browser is seeing anything "going wrong" in its developer console that we might have missed... and thank you for letting us know!

**Comment by williamaberry11** [comment]
I was using the Goggles on this page ([](https://webmaker.org/en-US/goggles)) when the bookmarklet was not working. I opened the Chrome console and saw this error: 
[Report Only] Refused to load the script 'https://goggles.webmaker.org/en-US/webxray.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' http://*.newrelic.com https://*.newrelic.com https://login.persona.org http://mozorg.cdn.mozilla.net https://mozorg.cdn.mozilla.net https://cdn.optimizely.com https://ssl.google-analytics.com".

I deleted the old Goggle bookmark and installed it again using the new webpage you referenced above and everything worked fine, despite working from the same browser. 

Thanks so much for the help and thanks for developing this tool!

**Comment by Pomax** [comment]
Oh that's interesting. Normally you get that error regardless of what you're trying to load (it's a notice that the website you're on doesn't allow people to just inject their own JS into the page), and quite a few pages these days try to enforce that. Good to hear the new goggles worked again, although I'm still curious why the old bookmarklet notice didn't work... Maybe we forgot to set an expiry date to make sure you got the new file, and it was trying to use the old file from the browser's cache. Worth for me to have a look at later. 

And glad to hear the updated bookmarklet works!
