### ISSUE TITLE
Don't let users accidentally miss the tutorial

### ISSUE THREAD

**Issue by hannahkane** [mozilla/x-ray-goggles#280]
Users are dismissing the lightbox that triggers the start of the tutorial.

Let's replace the [x] and make it a text link that says "click here to skip the tutorial" and have that close the dialog instead.

**Comment by Pomax** [comment]
![screenshot 181](https://cloud.githubusercontent.com/assets/177243/13543807/cecf6bf4-e223-11e5-83d7-0440779b5826.png)

**Comment by Pomax** [comment]
@hannahkane @kristinashu does that look reasonable?

**Comment by kristinashu** [comment]
@Pomax looks good but I think you can make that top right corner just a regular corner

**Comment by hannahkane** [comment]
Agree with what Kristina said. Looks good!

**Comment by Pomax** [comment]
The little lip had character! but, with it removed:

![screenshot 182](https://cloud.githubusercontent.com/assets/177243/13543974/717cf01e-e225-11e5-8474-38a1e49dd948.png)

**Comment by hannahkane** [comment]
+1

**Comment by kristinashu** [comment]
Cool, thanks!

**Comment by Pomax** [comment]
I wonder if the "by the way" part will now throw people off. E.g. open activity, read "on any website", go to a different tab and start the goggles, come back to the activity and be confused that "it didn't work".

Should we just remove that bit?

**Comment by hannahkane** [comment]
I see what you mean. I remember I advocated for that line initially, because I was worried it might seem like the Goggles would only work on this activity. But I guess this lightbox is really about the tutorial, not about using Goggles more generally, so I'm okay with the idea of removing that line.

**Comment by Pomax** [comment]
![screenshot 183](https://cloud.githubusercontent.com/assets/177243/13544113/4abcbc00-e227-11e5-81d3-7b486b8fb61e.png)

**Comment by hannahkane** [comment]
Yeah, this seems much less ambiguous. Nice job.

**Comment by Pomax** [comment]
deployed: https://goggles.mozilla.org/ftu
