### ISSUE TITLE
Xray goggles

### ISSUE THREAD

**Issue by hayleymiddletoncooke** [mozilla/x-ray-goggles#282]
I have hacked a website to create a new version for a school project but cannot publish it/save it. When I click publish it offers me the opportunity to sign in, but when I click the sign in button it takes me back to the website again.

**Comment by Pomax** [comment]
Hm, is this with the bookmarklet from https://goggles.mozilla.org? I just made sure to bookmark from there, and then opened a random websitte (in my case I picked http://flukeout.github.io), then when I pressed "publish" I was asked to sign in, but there were no oddities during that process, I filled in my username and password and then it showed me as logged in properly when it goes back to the page I'm trying to publish.

Do you have any details around what I tried and what you are seeing that are different?

**Comment by hayleymiddletoncooke** [comment]
Was late last night and I had logged off, but trying again now. When i
click public it gives me the option to sign in or create an account. When I
click sign it, it flashes to a screen where it seems to be loading the page
id.webmaker.org, but then quickly turns to the page offering me the choice
to sign in or create an account. I can't access any other options.

Any help greatly appreciated as need the resource I have created for Monday
morning!
Thanks,
Hayley

**Comment by Pomax** [comment]
Hm, that flash usually means you're loading id.webmaker.org to log in but you already have a valid session for it, so it immediately recognises it doesn't need to log you in further. Can you go to https://teach.mozilla.org, or https://thimble.mozilla.org and see if it either of those claims you are logged in? (they use the same login)? If not, try logging in to either one of those - that might "unstick" something that's gotten stuck specifically when using the goggles login option.

**Comment by hayleymiddletoncooke** [comment]
I was loggen in to mozilla, but logged out and tried again. This time it
asked me for my log in details but after I had entered them it still went
back to the sign up or log in screen.

I have tried it on a different computer, and it has let me publish, so
maybe something to do with my computer. however, once published the site
doesn't look as good as it does before it was published. It seems to have
reverted to a much simpler format. Is this normal?
Thanks,
H

**Comment by Pomax** [comment]
Only if you remixed an `http` site, rather than an `https` site - goggles publishes its remixes on a site hosted using `https`, the secure counterpart to the unsecured plain `http` protocol, and one aspect of `https` is that it will prevent loading of unsecured content (like .js and .css resources), so things can look rather different.

There's actually an issue open to make this more obvious when you start remixing that we can hopefully soon, to warn you that this is likely to happen if you start remixing an `http` rather than `https` website.

**Comment by hayleymiddletoncooke** [comment]
Thanks for explaining. I thought I was doing something wrong. I was remixing the BBC website which I think is http. I've taken screen shots of the remix and uploaded them to a presentation, so almost as good.
Thanks for your help.
Hayley.

**Comment by Pomax** [comment]
I will close this issue for now, but if you run into this again do let us know and we can maybe do some more detailed debugging.
